### ISSUE TITLE
'I2S_COMM_FORMAT_I2S' is deprecated and LittleFS error - Not compiling on Arduino 1.8.19 - Tests

### ISSUE THREAD

**Issue by fabiendostie** [ErichHeinemann/ESP32-Audio-Tests-ML#2]
Hi @ErichHeinemann ,
sorry to bother you with this.

On a fresh brand new install of arduinoIDE with only the required libraries for your sketch installedI and nothing extra I did this:
first:
Compiled and completed successfully both LittleFS tests (littleFS TIME and LittleFS TEST)
moved on to:
Compiled 3 different sketches using LittleFS successfully.
Finally:
Successfully Compiled 4 of M.License synth sketches
Then:
I tried to compile your Volca Beats sketch, in which I have only modified the I2S pinout and nothing else:
```
 * Define and connect your PINS to DAC here
 */
#define I2S_BCLK_PIN	27
#define I2S_WCLK_PIN	26
#define I2S_DOUT_PIN	25

From a completely fresh install of Arduino and all its sub folders and system dependencies.
```
All wires connected for the 3 Potentiometers and the button.
still... got these errors!

I2S error
```
/Users/lefab/Documents/_AAAArduino/Projects/ESP32-Audio-Tests-ML/ESP32-Volca-Beats-PCM-MOD_FAB2/i2s_interface.ino:104:49: warning: 'I2S_COMM_FORMAT_I2S' is deprecated [-Wdeprecated-declarations]
     .communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB),
                                                 ^~~~~~~~~~~~~~~~~~~
In file included from /Users/lefab/Library/Arduino15/packages/esp32/hardware/esp32/2.0.3/tools/sdk/esp32/include/driver/include/driver/i2s.h:16,
                 from /Users/lefab/Documents/_AAAArduino/Projects/ESP32-Audio-Tests-ML/ESP32-Volca-Beats-PCM-MOD_FAB2/i2s_interface.ino:6:
/Users/lefab/Library/Arduino15/packages/esp32/hardware/esp32/2.0.3/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:87:5: note: declared here
     I2S_COMM_FORMAT_I2S       __attribute__((deprecated)) = 0x01, /*!< I2S communication format I2S, correspond to `I2S_COMM_FORMAT_STAND_I2S`*/
     ^~~~~~~~~~~~~~~~~~~
/Users/lefab/Documents/_AAAArduino/Projects/ESP32-Audio-Tests-ML/ESP32-Volca-Beats-PCM-MOD_FAB2/i2s_interface.ino:104:71: warning: 'I2S_COMM_FORMAT_I2S_MSB' is deprecated [-Wdeprecated-declarations]
     .communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB),
                                                                       ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/lefab/Library/Arduino15/packages/esp32/hardware/esp32/2.0.3/tools/sdk/esp32/include/driver/include/driver/i2s.h:16,
                 from /Users/lefab/Documents/_AAAArduino/Projects/ESP32-Audio-Tests-ML/ESP32-Volca-Beats-PCM-MOD_FAB2/i2s_interface.ino:6:
/Users/lefab/Library/Arduino15/packages/esp32/hardware/esp32/2.0.3/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:88:5: note: declared here
     I2S_COMM_FORMAT_I2S_MSB   __attribute__((deprecated)) = 0x01, /*!< I2S format MSB, (I2S_COMM_FORMAT_I2S |I2S_COMM_FORMAT_I2S_MSB) correspond to `I2S_COMM_FORMAT_STAND_I2S`*/
     ^~~~~~~~~~~~~~~~~~~~~~~
```
littleFS error
```
/Users/lefab/Documents/Arduino/libraries/LittleFS_esp32/src/LITTLEFS.cpp: In member function 'virtual bool LITTLEFSImpl::exists(const char*)':
/Users/lefab/Documents/Arduino/libraries/LittleFS_esp32/src/LITTLEFS.cpp:44:28: error: no matching function for call to 'LITTLEFSImpl::open(const char*&, const char [2])'
     File f = open(path, "r");
                            ^
In file included from /Users/lefab/Documents/Arduino/libraries/LittleFS_esp32/src/LITTLEFS.cpp:17:
/Users/lefab/Library/Arduino15/packages/esp32/hardware/esp32/2.0.3/libraries/FS/src/vfs_api.h:38:17: note: candidate: 'virtual fs::FileImplPtr VFSImpl::open(const char*, const char*, bool)'
     FileImplPtr open(const char* path, const char* mode, const bool create) override;
                 ^~~~
/Users/lefab/Library/Arduino15/packages/esp32/hardware/esp32/2.0.3/libraries/FS/src/vfs_api.h:38:17: note:   candidate expects 3 arguments, 2 provided
```
Same board: espwroom-32
same dac: PCM5102A

please help me.

**Comment by ErichHeinemann** [comment]
Hi Fabien,
I have only a suggestion for You.
Take the Drumcomputer-Sketch from Marcel.
As You wrote in the email, it works with Your board.
Then change the MIDI-Notenumber to the number which are used by the Volca.

Thats what I did with my Volca-Beats PCM Mod.

I stopped doing electronic things a year ago after my last Windows-PC crashed and I went back making acoustic music.


Best Regards
Erich


Send from Iphone

**Comment by fabiendostie** [comment]
Ok, but I can't seem to figure out exactly how to integrate the
potentiometers and the push button with cc's and the midi I guess I'll
figure it out but I'm having a hard time, I'm still learning... Gerry
slowly I guess! I would appreciate any help at all.

Since last time we talked I have successfully built a fates (monome norns
clone) an orac synth based on raspberry Pi and a monome clone 128 grid and
a few potentiometer+fader  midi controllers, I do not understand what it
happening with your project and it really pisses me off. Not you, just the
fact that I can't freaking get it to work.

Anyways, if you could maybe guide me a little especially concerning the
pots and button that would be great

Thanks in advance.

Fabien Dostie
DIT/VR & Direction Technique - Coloriste Numérique -
DataWrangler, DIT & V/A
(AQTIS/IATSE)

**Comment by fabiendostie** [comment]
`That's what I did with my Volca-Beats PCM Mod.`


**Why do you think I'm asking for help exactly???**

You seem to think everybody knows how to code and that this is just a piece of cake because it's so basic and simple.
it's not, for me. Even though I have been getting so much better now, I still don't understand most, I can find what I need to copy-paste or sometimes understand parts... but it's not that easy... at all!!! 

I'm not asking for help because I'm lazy, I have been on this for over a year, and still, it does not work for me, no need to be **condescending**. I just never used any type of code before I started with Arduino 4 years ago. zero, niet, nada im learning and I'm trying the hardest I can.

Can I ask a question: How many users do you know are using your mod and unmodified code? am trying to ask around and look for users other than you and me and... well haven't found any...  I would have loved to ask them what/if did they change to make it work in a more general way?

no comments anywhere about it, isn't it weird knowing how popular the Volka serie is? Anytime I see anything about it, you are the sole commenter with no one saying how great it is or any comments at all for that matter. Not one...

Made me think, that maybe... there's a reason. Maybe not.

**Comment by ErichHeinemann** [comment]
Hi Fabien,

no, my code and the code from marcel are different. You wrote that all sketches from Marcel work and compile and only my one doesn´t. Then go with the sketch from Marcel.

Months ago I checked Your code, - replaced the pieces file by file with the files on GitHub.
Yes I have found one bug on Github and fixed it and added some instructions how to wire the pots in the PDF on Github.
The complied version worked on my hardware which is exactly the same hardware as You have.

I cannot help more, -  I give up with.

A hint to You search for a local Arduino-group or local Maker-Group and try to create something new based on the projects from Marcel.

Best Regards
Erich

**Comment by ErichHeinemann** [comment]
Hi Fabien,
yes Volcas were popular. Now the people are going with the Modular-Synths.
The PCM-Mod is to late.

I don’t sell PCM-Mods or make any money with it. I don’t even think to go into this DIY market. I only wanted to turn a focus into the great projects from Marcel.

Probably there are 0 users which have made a PCM-Mod - doesn’t matter. Honestly, the Volca is a great sounding analog drum computer without it. In my case it was only a fun-project to test the drum-computer from Marcel.
MIDI-Out from Volca into MIDI-In of the ESP32 … that’s only one cable.

I had some lazy days where I was searching for Volca-Mods and then I decided to push the ESp32 into the Volca housing.

Regards
Erich

**Comment by fabiendostie** [comment]
I am saying that I have a feeling you should not share your code, because apparently... it does not build anymore with the newer versions of Arduino 2 other friends tried your code and instructions and it doesn't even compile.  and You seem to be the only one who has any success with it. maybe it's written in  a way that is too specific to your exact equipment. I dont know. it's just frustrating, I seriously started with your code more than a year ago, and after so many fresh starts and re-installs every time no success. If I were you, I would remove it from the public and wait to have tested it correctly with VS code or something so that not only you can benefit from it... out of 4  people, 5 including you there is only one that had success and that's you... pretty low average... It's not showcasing Marcel's work at all if it's not working like ALL of his stuff!

I just asked for help with the configuration of the midi  cc because I do not understand that bit...
I have built A fates norns, A monome grid, 4 Synths including a moog clone, a euclidian and 32 step probability sequencer since...  Definitely, I'm not that dumb.

**Comment by ErichHeinemann** [comment]
Hi Fabien, I haven´t said You are a dumb.
There are many projects on github which are in a stage where they are not in the best form.
I could be the truth, that it only compiles with Arduino IDE 1.8.19 as it was the suggestion from the ESP32-Arduino-developers to use this as the best choise when I did it last year.

Why should I check to compile something with a new version Arduino 2.0 RC - release candidate?
But thankYou for this hint, I didn´t check these updates.

For now, I would say, this project only could be compiled with IDE 1.8.19.
I won´t update to 2.0 RC - Version.

Regards
Erich

**Comment by fabiendostie** [comment]
not using arduino 2, it's not fully released... by the way... never use a beta or RC for production material. i'm using 1.8.19

**Comment by fabiendostie** [comment]
So..;. let me understand, you haven't tried it or have someone, anyone else try and compile other than you on your specific model of esp32 + DAC? not a single other one? ... maybe then just change to add something to say that, to tell people that this has not been tested AT ALL!

**Comment by ErichHeinemann** [comment]
Hi FabienDostie, I have added some comment it the Readme for this project.
I have compiled the code on multiple boards, on a breadboard-installation, and with different I2S-PCM-Boards.

I don´t take down this code. I added the hint, that it does not compile on Arduino IDE 2.0. I never suggested that it compiles on Ardiuno IDE 2.0 RC. or on VSS. 
Please simply ignore my projects.

**Comment by fabiendostie** [comment]
I don't know why you are talking about arduino 2.0.

I AM **NOT** USING ARDUINO IDE 2.0, AND IT'S NOT COMPILING.

NOT COMPILING ON ARDUINO 1.8.19 EITHER!! EVEN A FRESH INSTALL WITH ALL FRESHLY DOWNLOADED LIBRARIES AND BOARD MODULES. ON A ESP32DEV v1.

SHOULD AT LEAST COMPILE

Thanks for the hint, because it might help others to choose and not lose time on this project, which is not ready for release to the public.

**Comment by ErichHeinemann** [comment]
Hi Fabien,
You wrote it some days ago ..

...
 it does not build anymore with the newer versions of Arduino 2 other friends trie
...

Sorry, I am not here to fight with You…. It were Your words.

Regards
Erich

**Comment by fabiendostie** [comment]
I said " i am using the latest build of Arduino IDE" which is 1.8.19... never used the words v2, beta or release candidate... so latest stable and official release is 1.8.19.... I guess you assumed I meant 2.0.... but it's not the case.

BY THE WAY i just received 3 more models of esp 32 and the exact same pcm5102 as you are using with your wiring and folowing the exact procedure on each of them.... 6 different esp32 models... and it still just does not compile... not just no sound, not even compiling sir.... there is a problem with your code. maybe you modified it and you forgot, maybe you have a library that makes it work, but that isn<t required specifically... who knows... very frustrating, specially that now I have tried it with the EXACT SAME MODEL OF ESP32 and dac as you... same issue.... cant build even the unmodified code. 100% identical straight from github, not compiling on IDE 1.8.19

**Comment by ErichHeinemann** [comment]
Hi Fabien,
are You using Linux?


Regards
Erich

**Comment by fabiendostie** [comment]
I have linux, a mac and a pc and android…. but i am trying to build from a Mac, and a pc… mostly Mac.;)
why?

**Comment by ErichHeinemann** [comment]
In my case, littelFS does not work on my MAC.
Marcel Licence mentioned the question. … LittleFS has Problems on Linux too … I did not verify it.

I did my programming in an old Windows-PC .. there, the littleFS-Tools work fine. I didn’t get them up and running on my old MAC with Intel CPU and my newer M1 … didn’t even try to install Android IDE on it..

Perhaps this was a fault to use these libraries which work mostly on Windows.
I only used the MIDI-Lib from foutyseveneffects which Marcel did not use.

Best Regards
Erich


> Am 19.05.2022 um 22:32 schrieb fabiendostie ***@***.***>:
> 
> 
> I have linux, a mac and a pc and android…. but i am trying to build from a Mac, and a pc… mostly Mac.;)
> why?
> 
>

**Comment by fabiendostie** [comment]
I use fortyseven midi library for other projects on my mac. but I have tried to build your project on my PC and i get the same errors.
It's okay i tried hard and itès not working for me. sad about it but what are you going to do.

I might try on a 4th and last model of DAC this end of week, but after that... i'll abandon the idea to do this with your code.
